import {
  ContentContainer,
  createHsafaArtifactStore,
  HsafaChat,
  HsafaProvider,
  useChatArtifact,
  useChatArtifactVersioning,
  useHsafaActiveChatId,
  useHsafaTools,
} from '@hsafa/ui-sdk';
import type { ReactNode } from 'react';
import { useEffect, useMemo, useState } from 'react';
import DeckGLMap from './DeckGLMap';
import type { MapConfig } from './types';
import { createDeckGLMapTools } from '../../tools/deckglMapTools';

const AGENT_ID = import.meta.env.VITE_AGENT_ID_DECKGL_MAP || 'cmisy479x0001qglw77xrr8pw';
const AGENT_BASE_URL = import.meta.env.VITE_HSAFA_BASE_URL || 'http://localhost:3900';

type SetState<T> = (updater: T | ((prev: T) => T)) => void;

type ToolUIProps = {
  input: unknown;
  toolName: string;
  toolCallId: string;
  output?: unknown;
  status?: string;
};

const mapConfigStore = createHsafaArtifactStore<MapConfig>({
  namespace: 'deckgl-map-configs',
});

const EMPTY_MAP_CONFIG: MapConfig = {
  title: 'AI DeckGL Map',
  description: 'Generated by AI tools',
  mapStyle: '/martin/style-dark.json',
  initialViewState: {
    longitude: 46.7,
    latitude: 24.7,
    zoom: 10.5,
    pitch: 45,
    bearing: 0,
  },
  layers: [],
};

const asRecord = (v: unknown): Record<string, unknown> => {
  if (v && typeof v === 'object') return v as Record<string, unknown>;
  return {};
};

const isRunningStatus = (status?: string) => {
  const s = (status || '').toLowerCase();
  if (!s) return false;
  if (s === 'input-streaming') return true;
  if (s === 'input-available') return true;
  if (s.includes('run') || s.includes('pending') || s.includes('loading') || s.includes('stream')) return true;
  return false;
};

function ToolCard(props: ToolUIProps & { title: string; summary?: string; children?: ReactNode }) {
  const running = isRunningStatus(props.status);
  return (
    <div style={{
      borderRadius: '14px',
      border: '1px solid rgba(255,255,255,0.08)',
      background: 'linear-gradient(135deg, rgba(26,27,30,0.9) 0%, rgba(23,24,28,0.95) 100%)',
      padding: '14px 14px',
      marginTop: '10px',
      boxShadow: running
        ? '0 12px 40px rgba(0,0,0,0.25), 0 0 0 1px rgba(99,102,241,0.28)'
        : '0 12px 40px rgba(0,0,0,0.25)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' }}>
        <div style={{ minWidth: 0 }}>
          <div style={{
            fontSize: '13px',
            fontWeight: 700,
            color: '#FFFFFF',
            letterSpacing: '-0.01em',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          }}>
            {props.title}
          </div>
          {props.summary ? (
            <div style={{
              fontSize: '12px',
              color: '#9CA3AF',
              marginTop: '4px',
              lineHeight: 1.4,
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
            }}>
              {props.summary}
            </div>
          ) : null}
        </div>

        <div style={{
          fontSize: '11px',
          fontWeight: 700,
          padding: '4px 10px',
          borderRadius: '999px',
          backgroundColor: running ? 'rgba(99,102,241,0.14)' : 'rgba(34,197,94,0.15)',
          border: running ? '1px solid rgba(99,102,241,0.35)' : '1px solid rgba(34,197,94,0.35)',
          color: running ? '#A78BFA' : '#22C55E',
          textTransform: 'capitalize',
          flexShrink: 0,
        }}>
          {running ? 'In progress' : 'Done'}
        </div>
      </div>

      {props.children}
    </div>
  );
}

function SetMapConfigToolUI(props: ToolUIProps) {
  const input = asRecord(props.input);
  const config = asRecord(input.config ?? input);
  const title = typeof config.title === 'string' ? config.title : undefined;
  const layers = Array.isArray(config.layers) ? config.layers : undefined;
  const count = typeof layers?.length === 'number' ? layers.length : undefined;
  const running = isRunningStatus(props.status);

  return (
    <ToolCard
      {...props}
      title={running ? 'Applying map config…' : 'Map config applied'}
      summary={`${title ? `${title} · ` : ''}${typeof count === 'number' ? `${count} layer(s)` : ''}`}
    />
  );
}

function UpdateMapConfigToolUI(props: ToolUIProps) {
  const input = asRecord(props.input);
  const path = typeof input.path === 'string' ? input.path : undefined;
  const running = isRunningStatus(props.status);

  return (
    <ToolCard
      {...props}
      title={running ? 'Updating map config…' : 'Map config updated'}
      summary={path ? `Path: ${path}` : undefined}
    />
  );
}

function ReadMapConfigToolUI(props: ToolUIProps) {
  const output = asRecord(props.output);
  const data = asRecord(output.data);
  const config = asRecord(data.config);
  const title = typeof config.title === 'string' ? config.title : undefined;
  const layers = Array.isArray(config.layers) ? config.layers : undefined;
  const count = typeof layers?.length === 'number' ? layers.length : undefined;

  return (
    <ToolCard
      {...props}
      title={'Current map config'}
      summary={`${title ? `${title} · ` : ''}${typeof count === 'number' ? `${count} layer(s)` : ''}`}
    />
  );
}


const HsafaUI: Record<string, (props: ToolUIProps) => ReactNode> = {
  set_map_config: SetMapConfigToolUI,
  update_map_config: UpdateMapConfigToolUI,
  read_map_config: ReadMapConfigToolUI,
};

export default function MapAgentPage() {
  return (
    <HsafaProvider baseUrl={AGENT_BASE_URL}>
      <ContentContainer>
        <MapAgentPageContent />
      </ContentContainer>
    </HsafaProvider>
  );
}

function MapAgentPageContent() {
  const activeChat = useHsafaActiveChatId({ agentId: AGENT_ID });
  const activeChatId = activeChat.chatId;

  const [stableChatId, setStableChatId] = useState<string | undefined>(activeChatId);

  useEffect(() => {
    if (!activeChatId) return;
    const timer = window.setTimeout(() => {
      setStableChatId(activeChatId);
    }, 0);
    return () => {
      window.clearTimeout(timer);
    };
  }, [activeChatId]);

  const { value: mapConfig, setValue: setMapConfig } = useChatArtifact<MapConfig>({
    agentId: AGENT_ID,
    chatId: stableChatId,
    initial: EMPTY_MAP_CONFIG,
    store: mapConfigStore,
    saveDebounceMs: 800,
  });

  const versioning = useChatArtifactVersioning<MapConfig>({
    chatId: stableChatId,
    store: mapConfigStore,
    value: mapConfig,
    setValue: setMapConfig,
    initial: EMPTY_MAP_CONFIG,
  });

  const mapToolsObj = useMemo(
    () =>
      createDeckGLMapTools(
        () => mapConfig,
        setMapConfig as unknown as SetState<MapConfig>
      ),
    [mapConfig, setMapConfig]
  );

  const mapTools = useHsafaTools({
    state: mapConfig,
    setState: setMapConfig as unknown as SetState<MapConfig>,
    tools: () => mapToolsObj,
  });

  const canRenderMap = Array.isArray(mapConfig.layers) && mapConfig.layers.length > 0;

  return (
    <>
      <div style={{ flex: 1, overflow: 'hidden' }}>
        {!stableChatId && !canRenderMap ? (
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '500px',
            background: 'linear-gradient(135deg, #1a1b1e 0%, #17181c 100%)',
            border: '2px dashed #2A2C33',
            borderRadius: '16px',
            padding: '48px 24px',
            margin: '24px',
          }}>
            <div style={{ textAlign: 'center', maxWidth: '540px' }}>
              <h3 style={{ margin: 0, fontSize: '24px', fontWeight: 600, color: '#FFFFFF' }}>
                Open the chat to generate a map
              </h3>
              <p style={{ marginTop: '12px', color: '#888', fontSize: '14px', lineHeight: '1.6' }}>
                Each chat has its own map configuration. Ask the assistant to create layers and queries.
              </p>
            </div>
          </div>
        ) : canRenderMap ? (
          <DeckGLMap config={mapConfig} onError={(err) => console.error('DeckGL Error:', err)} />
        ) : (
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '500px',
            background: 'linear-gradient(135deg, #1a1b1e 0%, #17181c 100%)',
            border: '2px dashed #2A2C33',
            borderRadius: '16px',
            padding: '48px 24px',
            margin: '24px',
          }}>
            <div style={{ textAlign: 'center', maxWidth: '540px' }}>
              <h3 style={{ margin: 0, fontSize: '24px', fontWeight: 600, color: '#FFFFFF' }}>
                No layers yet
              </h3>
              <p style={{ marginTop: '12px', color: '#888', fontSize: '14px', lineHeight: '1.6' }}>
                Ask the assistant to call set_map_config with at least one layer.
              </p>
            </div>
          </div>
        )}
      </div>

      <HsafaChat
        agentId={AGENT_ID}
        theme="dark"
        title="DeckGL Map Agent"
        placeholder="Describe the map you want to generate…"
        primaryColor="#F97316"
        accentColor="#FB7185"
        alwaysOpen={true}
        expandable={false}
        HsafaTools={mapTools}
        HsafaUI={HsafaUI}
        onMessagesChange={(messages: unknown[], chatId?: string) => {
          if (chatId) setStableChatId(chatId);
          void versioning.onMessagesChange(messages, chatId);
        }}
        onFinish={(payload: unknown) => {
          void versioning.onFinish(payload);
        }}
        presetPrompts={[
          {
            label: '🏫 Schools + Students',
            prompt: 'Create a map config with two scatterplot layers: schools (green) and students (blue). Use ClickHouse queries and cast lon/lat to Float64. Center on Riyadh.',
          },
          {
            label: '🔥 Student density',
            prompt: 'Create a hexagon density layer for students. Use ClickHouse query selecting lon/lat as Float64. Use maxRows 50000 and a good default viewState.',
          },
          {
            label: '👁️ Show current config',
            prompt: 'Call read_map_config and summarize the config (title, viewState, layers).',
          },
        ]}
      />
    </>
  );
}
